"""Add uniq name constraint

Revision ID: f65311ba07c8
Revises: 2e6ce6970e87
Create Date: 2022-08-22 18:11:47.260552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f65311ba07c8'
down_revision = '2e6ce6970e87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'accounts', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='unique')
    # ### end Alembic commands ###
